apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-files
  namespace: demo
data:
  policy.yaml: |
    apiVersion: json.kyverno.io/v1alpha1
    kind: ValidatingPolicy
    metadata:
      name: checkrequest
    spec:
      rules:
        - name: deny-guest-request
          assert:
            all:
            - message: "GET method calls at path /foo are not allowed to guest"
              check:
                request:
                    http:
                        method: GET
                        headers:
                            authorization:
                                (base64_decode(split(@, ' ')[1])): 
                                    (split(@, ':')[0]): alice
                        path: /foo        
                     