---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-sidecar-injector
  namespace: sidecar-injector
  labels:
    app.kubernetes.io/name: sidecar-injector
    app.kubernetes.io/instance: sidecar-injector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-sidecar-injector
  labels:
    app.kubernetes.io/name: sidecar-injector
    app.kubernetes.io/instance: sidecar-injector
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-sidecar-injector
  labels:
    app.kubernetes.io/name: sidecar-injector
    app.kubernetes.io/instance: sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-injector
subjects:
  - kind: ServiceAccount
    name: kubernetes-sidecar-injector
    namespace: sidecar-injector
---
